# This is a simple powershell command execution task for Dev Box.
$schema: "1.0"
name: install-vscode-extension
description: Install a VSCode extension using the code or code-insiders command.
author: Francesco Sodano
command: ".\\install-vscode-extension.ps1 -package {{package}} -RunAsUser {{runAsUser}}"
parameters:
  package:
    type: string
    default: ""
    required: true
    description: The package to install.
  runAsUser:
    type: boolean
    default: false
    required: false
    description: execute the command when the user login the devbox at the first time.
documentation:
  notes: This task is used to install a VSCode extension using the code or code-insiders command..
  examples:
    - name: install-vscode-extension
      description: install ms-python.python extension
      parameters:
        package: ms-python.python
    - name: install-vscode-extension
      description: install ms-python.python extension as user
      parameters:
        command: ms-python.python
        runAsUser: true