$schema: "1.0"
name: powershell
description: Execute a powershell command.
author: Francesco Sodano
command: ".\\Run-Command.ps1 -Command {{command}} -WorkingDirectory {{workingDirectory}} -PS7 {{PS7}} -RunAsUser {{runAsUser}}"
parameters:
  command:
    type: string
    default: ""
    required: true
    description: The command to execute.
  workingDirectory:
    type: string
    default: ""
    required: false
    description: The working directory to execute the command in.
  PS7:
    type: boolean
    default: false
    required: false
    description: execute the command using PowerShell 7.
  runAsUser:
    type: boolean
    default: false
    required: false
    description: execute the command when the user login the devbox at the first time.
documentation:
  notes: This task is used to execute a powershell command.
  examples:
    - name: powershell
      description: print hello world
      parameters:
        command: "Write-Host 'hello, world!'"
    - name: powershell
      description: run script
      parameters:
        command: "./script.ps1"
        workingDirectory: C:\\provisioning\\temp
    - name: powershell
      description: run script with PowerShell 7
      parameters:
        command: "Write-Host 'hello, world!'"
        PS7: true
    - name: powershell
      description: run script when the user login the devbox at the first time
      parameters:
        command: "Write-Host 'hello, world!'"
        runAsUser: true